config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
    
  resources :admins do
    member do 
      get :get_dates
    end
    collection do
      get :destroy_users
    end
  end
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/admins/_form.html.erb
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>
  <body  style="padding: 5%;>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

<%= form_with(model: admin) do |form| %>
  <% if admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
        <% admin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" style="padding-top: 5%">
    <%= form.text_field :scheduleName, :required => true , placeholder:" Schedule Name", class: "form-control",:style=> 'max-width: 33%;min-width: 85%;' %>
    <br>
    <br>
    <%= form.text_field :dateRange, :required => true , placeholder:"Date Range (YYYY-MM-DD:YYYY-MM-DD)", class: "form-control",:style=> 'max-width: 33%;min-width: 85%;' %>
    <br>
    <br>
    <%= form.text_field :timeRange, :required => true , placeholder:"Time Range (XX:XXam - XX:XXpm)", class: "form-control",:style=> 'max-width: 33%;min-width: 85%;' %>
    <br>
    <br>
    <%= form.text_field :interviewLength, :required => true , placeholder:"Interview Length (mins)", class: "form-control",:style=> 'max-width: 33%;min-width: 85%;' %>
    <br>
    <br>
    <%= form.text_field :numBreaks, :required => true , placeholder:"Break every __ interviews", class: "form-control",:style=> 'max-width: 33%;min-width: 85%;' %>
    <br>
    <br>
    <%= form.text_field :numRooms, :required => true , placeholder:"Number of Rooms", class: "form-control",:style=> 'max-width: 33%;min-width: 85%;' %>
  </div>

  <center>
  <div class="actions">
    <%= form.submit "Submit", class: "btn btn-primary" %>
    <%= link_to 'Back', admins_path, class:'btn btn-dark' %>
  </div>
  
  </center>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form', admin: @admin %>

app/views/admins/index.html.erb
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <p id="notice"><%= notice %></p>
    <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="#">
        <img id="logo" src="https://upload.wikimedia.org/wikipedia/commons/a/aa/Zachry_Leadership_Program_Logo.jpg" width="330" height="70" class="d-inline-block align-top" alt="">
        </a>
    </nav>
</head>
<body>
    <div style="padding:2%; margin-right: 5%;">
    <center>
        <h1>Interviews scheduled:</h1>
    </center>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Phone Number</th>
                <th>Email </th>
                <th>Interview Date</th>
                <th>Interview Time  </th>
                <th colspan="5"></th>
            </tr>
        </thead>
        <tbody>
            <% dt_array = [] %>
            <% @users.sort_by(&:interviewDateTime).each do |user| %>
            <% dt_array.push([user.interviewDateTime.split(/,/)[0], user.interviewDateTime.split(/,/)[1], user]) %>
            <% end %>
            <% dt_array.each do |dt| %>
            <% if dt[1].to_s.include? "am"%> 
            <% dt[1] = dt[1].split(/:/)[0].to_i + dt[1].split(/:/)[1].to_i/60 %>
            <% elsif dt[1].to_s.include? "pm"%> 
            <% if dt[1].split(/:/)[0].to_i == 12%> 
            <% dt[1] = dt[1].split(/:/)[0].to_i + dt[1].split(/:/)[1].to_i/60 %>
            <% else %>
            <% dt[1] = dt[1].split(/:/)[0].to_i + 12 + dt[1].split(/:/)[1].to_i/60 %>
            <% end %>
            <% end %>
            <% dt[1] = dt[1].to_i %>
            <% end %>
            <% dt_array = dt_array.sort_by {|d,t| [d, t]} %>
            <% dt_array.each do |l| %>
            <% user = l[2] %>
            <% #if user.interviewDateTime.split(/,/)[0] >= start_date.to_s and user.interviewDateTime.split(/,/)[1] <= end_date.to_s %>
            <% #next %>
            <% #end %>
            <%if !user.phoneNumber.include? "-" %>
            <%new_phoneNumber = user.phoneNumber[0..2].to_s + "-" + user.phoneNumber[3..5].to_s + "-" + user.phoneNumber[6..9].to_s %>
            <%else%>
            <%new_phoneNumber = user.phoneNumber%>
            <%end%>
            <tr>
                <td><%= user.name %></td>
                <td><%= new_phoneNumber %></td>
                <td><%= user.email %></td>
                <td><%= user.interviewDateTime.split(/,/)[0] %></td>
                <td><%= user.interviewDateTime.split(/,/)[1] %></td>
                <td><%= link_to 'Edit', edit_user_path(user), class:'btn btn-warning btn-sm', style:'color: white'%></td>
                <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger btn-sm', id:'whiteIt'%></td>
            </tr>
            <% end %>
        </tbody>
    </table>
    <br>
    <%= link_to 'Delete All Users', destroy_users_admins_path, data: { confirm: 'Are you sure?' }, class:'btn btn-danger btn-sm', id:'whiteIt'%>
    <center>
        <br>
        <br>
        <h1>List of Schedules:</h1>
    </center>
    <table>
        <thead>
            <tr>
                <th>Schedule Name</th>
                <th>Date Range</th>
                <th>Time Range</th>
                <th>Interview Length</th>
                <th>Break after __ interviews</th>
                <th>Number of rooms</th>
                <th colspan="6"></th>
            </tr>
        </thead>
        <tbody>
            <% @admins.each do |admin| %>
            <tr>
                <td><%= admin.scheduleName %></td>
                <td><%= admin.dateRange%></td>
                <td><%= admin.timeRange%></td>
                <td><%= admin.interviewLength%></td>
                <td><%= admin.numBreaks%></td>
                <td><%= admin.numRooms%></td>
                <td><%= link_to 'Show', admin, class:'btn btn-primary btn-sm', id:'whiteIt'%></td>
                <td><%= link_to 'Edit', edit_admin_path(admin), class:'btn btn-warning btn-sm', id:'whiteIt'%></td>
                <td><%= link_to 'Delete', admin, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger btn-sm', id:'whiteIt'%></td>
            </tr>
            <% end %>
        </tbody>
    </table>
    <br>
    <%= link_to 'New Schedule', new_admin_path, class:'btn btn-success', id:'whiteIt' %>
    <%= link_to 'Help', href="/tutorial_admin.pdf", class:'btn btn-secondary', id:'whiteIt' %>

    </div>

app/views/admins/new.html.erb
<h1>New Schedule</h1>
<div>
<%= render 'form', admin: @admin %>

</div>

app/views/admins/show.html.erb
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>
  <body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


<p id="notice"><%= notice %></p>
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="#">
    <img id="logo" src="https://upload.wikimedia.org/wikipedia/commons/a/aa/Zachry_Leadership_Program_Logo.jpg" width="330" height="70" class="d-inline-block align-top" alt="">
  </a>
</nav>
<h1 style="text-align:center"> <center> Schedule Details: </center></h1>
<center>
<ui style="list-style-type:none">
  <li>
    <strong>Schedule Name:</strong>
    <%= @admin.scheduleName %>
  </li>
  <br>
  <li>
    <strong>Date Range:</strong>
    <%= @admin.dateRange%>
  </li>
  <br>
  <li>
    <strong>Time Range:</strong>
    <%= @admin.timeRange%>
  </li>
  <br>
  <li>
    <strong>Interview Length:</strong>
    <%= @admin.interviewLength %>
  </li>
  <br>
  <li>
    <strong>Number of Breaks:</strong>
    <%= @admin.numBreaks%>
  </li>
</ui>
</center>
<br>
<center>
<%= link_to 'Edit', edit_admin_path(@admin), class:'btn btn-warning', id:'whiteIt'%> 
<%= link_to 'Back', admins_path, class:'btn btn-dark', id:'whiteIt'%>
</center>