config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
    
  resources :admins do
    member do 
      get :get_dates
    end
    collection do
      get :destroy_users
    end
  end
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true
    validates :phoneNumber, presence: true
    validates :email, presence: true
    validates :interviewDateTime, presence: true
    validates_format_of :email, :with => /\A(.+)@(tamu.edu)\z/, :message => "must end with @tamu.edu"
    validate :phone_validator
    validate :times_not_taken

    def phone_validator
        #phone_regex = /\A([0-9]{3})-([0-9]{3})-([0-9]{4})\z/
        phone_regex = /\A([0-9]{10})\z/
        phone_regex2 = /\A([0-9]{3})-([0-9]{3})-([0-9]{4})\z/
        phone_number= "Phone Number"
        if phoneNumber.blank? || (!phoneNumber.match(phone_regex) && !phoneNumber.match(phone_regex2))
            self.errors.add(:phone_number, 'must be of format: xxx-xxx-xxxx')
        end
    end

    def times_not_taken
        new_dt_list = User.list_days_and_times
        interview_date_and_time = "Interview date and time"
        if !new_dt_list.include? interviewDateTime
            self.errors.add(:interview_date_and_time, 'has been taken by someone else. Please try again')
        end

    end

=begin
    def self.get_dates
        #start_date = Admin.dateRange.split(/-/)[0]
        #end_date = Admin.dateRange.split(/-/)[1]
        @admins = Admin.all
        my_date = ""
        @admins.each do |a|
            my_date = a.dateRange
        end
        return my_date
    end

    def self.get_times
        @admins = Admin.all
        my_time = ""
        @admins.each do |a|
            my_time = a.timeRange
        end
        #start_time = my_time.split(/-/)[0].rstrip.split("am")
        #end_time = my_time.split(/-/)[1].rstrip.split("pm")
        start_time = my_time.split(/-/)[0].rstrip
        end_time = my_time.split(/-/)[1].rstrip

        if start_time.include? "am"
            start_time = start_time.split("am")[0]
            start_time = start_time.split(":")[0].to_i  # gets the hour, and uses it as start
        elsif start_time.include? "pm"
            start_time = start_time.split("pm")[0]
            start_time = start_time.split(":")[0].to_i + 11 # gets the hour, and uses it as start
        end

        if end_time.include? "am"
            end_time = end_time.split("am")[0]
            end_time = end_time.split(":")[0].to_i  # gets the hour, and uses it as start
        elsif end_time.include? "pm"
            end_time = end_time.split("pm")[0]
            end_time = end_time.split(":")[0].to_i + 11 # gets the hour, and uses it as start. Plus 11 because time includes 30 minute from end time
        end

        puts(start_time)
        puts(end_time)
        return [start_time, end_time]
    end

=end
    def self.list_days_and_times
        @admins = Admin.all

        my_date = ""
        num_breaks = ""
        interview_length = ""
        my_time = ""
        num_rooms = ""
        @admins.each do |a|
            my_date = a.dateRange
            num_breaks = a.numBreaks
            interview_length = a.interviewLength
            my_time = a.timeRange
            num_rooms = a.numRooms
        end
        #2021-10-06:2021-10-07
        start_date = Date.parse(my_date.split(/:/)[0].to_s)
        end_date = Date.parse(my_date.split(/:/)[1].to_s)
        date_list = (start_date..end_date).map(&:to_s) #date list finished
        #return date_list

        # time list parsing
        start_time = my_time.split(/-/)[0].rstrip
        end_time = my_time.split(/-/)[1].rstrip

        if start_time.include? "am"
            start_time = start_time.split("am")[0]
            start_time = start_time.split(":")[0].to_i  # gets the hour, and uses it as start
        elsif start_time.include? "pm"
            start_time = start_time.split("pm")[0]
            start_time = start_time.split(":")[0].to_i + 11 # gets the hour, and uses it as start
        end

        if end_time.include? "am"
            end_time = end_time.split("am")[0]
            end_time = end_time.split(":")[0].to_i  # gets the hour, and uses it as start
        elsif end_time.include? "pm"
            end_time = end_time.split("pm")[0]
            end_time = end_time.split(":")[0].to_i + 11 # gets the hour, and uses it as start. Plus 11 because time includes 30 minute from end time
        end

        x = start_time
        min = 0
        time_list = []
        while x <= end_time
            if(x <= 12)
                if min == 0
                    min = "00"
                end
                if x == 12
                    time_list.push(x.to_s + ":" + min.to_s + "pm")
                else
                    time_list.push(x.to_s + ":" + min.to_s + "am")
                end
            else
                if min == 0
                    min = "00"
                end
                time_list.push((x-12).to_s + ":" + min.to_s + "pm")
            end

            # increase minute by interview length
            min = min.to_i + interview_length.to_i
            if min == 60
                min = 0
            end
            if min != 0
                x = x
            else
                x = x + 1
            end
        end


        #puts (time_list)
        #return time_list

        # remove time slot every __ interviews
        # break time is equal to interview time
        break_count = 0
        i = 0

        time_list.each do |t|
            if break_count == num_breaks.to_i
                time_list.delete_at(i)
                break_count = 0
            end
            break_count = break_count + 1
            i = i + 1
        end


        date_time_dict = {}
        date_list.each do |dt|
            time_list.each do |t|
                date_time_dict[dt.to_s + "," + t.to_s] = num_rooms.to_i
            end
        end

        @users = User.all
        used_date_and_time = []
        @users.each do |u|
            if u.interviewDateTime.split(/,/)[0] >= start_date.to_s and u.interviewDateTime.split(/,/)[0] <= end_date.to_s
                used_date_and_time.push(u.interviewDateTime)
            end
        end


        used_date_and_time.each do |dt|
            date_time_dict[dt] = date_time_dict[dt] - 1
        end

        final_date_time_list = []
        date_time_dict.keys.each do |dt|
            if date_time_dict[dt] > 0
                final_date_time_list.push(dt)
            end
        end


        return final_date_time_list 
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
    @admins = Admin.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @admin = Admin.all
    if @admin.exists?
      @user = User.new
    else
      respond_to do |format|
        format.html { render js: "No schedule found"}
      end
    end
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user }
        UserMailer.with(user: @user).user_confirmation.deliver_later
        UserMailer.with(user: @user).admin_confirmation.deliver_later
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admins_url, notice: "User was successfully updated." }
        UserMailer.with(user: @user).user_confirmation.deliver_later
        UserMailer.with(user: @user).admin_confirmation.deliver_later
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admins_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :phoneNumber, :email, :interviewDateTime)
    end

    def access_admin
      @admins = Admin.all
    end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_form.html.erb
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>
  <body  style="padding: 5%;>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" style="padding-top: 5%">
    <%= form.text_field :name, :required => true , placeholder:"Name", class: "form-control",:style=> 'max-width: 33%;min-width: 85%;' %>
    <br>
    <br>
    <%= form.text_field :phoneNumber, :required => true, placeholder:"Phone Number (format: xxx-xxx-xxxx)", class: "form-control",:style=> 'max-width: 33%;min-width: 85%;'   %>
    <br>
    <br>
    <%= form.text_field :email, :size => "10", :required => true, placeholder:"TAMU Email", class: "form-control", :style=> 'max-width: 33%;min-width: 85%;'   %>
    <br>
    <br>
    <%= cur_date = "" %>
    <% User.list_days_and_times.each do |date_time| %>
      <% new_date = date_time.split(/,/)[0] %>
      <% if new_date != cur_date %>
        <% day_of_week = DateTime.parse(new_date).to_date.strftime("%A") %>
        <br>
        <%= form.label "Interview Date: " + day_of_week + ", "+ new_date, style: 'font-weight: bold; text-transform: capitalize;' %>
        <br>
        <% cur_date = new_date %>
      <% end %>
      <%= form.radio_button :interviewDateTime, [date_time] %> <%= date_time.split(/,/)[1] %><br>
    <% end %>
  </div>

  <center>
  <div class="actions">
    <%= form.submit "Submit", class: "btn btn-primary" %>
    <%= link_to 'Back', root_path, class: "btn btn-dark"  %>
    <%= link_to 'Help', href="/tutorial_user.pdf", class:'btn btn-secondary', id:'whiteIt' %>

  </div>
  
  </center>
<% end %>


</body>

app/views/users/edit.html.erb
<h1>Editing Interview</h1>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>
  <body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


<p id="notice"><%= notice %></p>
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="#">
    <img id="logo" src="https://upload.wikimedia.org/wikipedia/commons/a/aa/Zachry_Leadership_Program_Logo.jpg" width="330" height="70" class="d-inline-block align-top" alt="">
  </a>

</nav>

<center>
<h1>Welcome to the Zachry Leadership Program Interview Scheduler!</h1>
<br>


<%= link_to 'Schedule Interview', new_user_path, class:'btn btn-success', id:'whiteIt' %>

</center>
</body>

app/views/users/new.html.erb
<div id= "newmain">
    <h3>New Interview</h3>
</div>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>
  <body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


<p id="notice"><%= notice %></p>
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="#">
    <img id="logo" src="https://upload.wikimedia.org/wikipedia/commons/a/aa/Zachry_Leadership_Program_Logo.jpg" width="330" height="70" class="d-inline-block align-top" alt="">
  </a>
</nav>
<div style="padding:2%; margin-right: 5%;">
<h1 style="text-align:center"> <center> Thank You for signing up </center></h1>
<center>
<br>
<br>
    <ui style="list-style-type:none">
      <li>
        <strong>Name:</strong>
        <%= @user.name %>
      </li>
      <li>
        <strong>Interview Date:</strong>
        <%= @user.interviewDateTime.split(/,/)[0] %>
      </li>
      <li>
        <strong>Interview Time:</strong>
        <%= @user.interviewDateTime.split(/,/)[1] %>
      </li>
    </ui>
 
 <br>
<center>
<p style="text-align:center;">
<br>
  <strong style="text-align:center;">Please screenshot for your records, and email seth.sullivan@tamu.edu if you need to reschedule.</strong>
</p>
<br>
<center>
<%= link_to 'Back', users_path, class:'btn btn-dark', id:'whiteIt'%>
</center>
</div>